services:
  db:
    image: postgres:latest
    environment: 
      - POSTGRES_PASSWORD=password
      - DB_HOST=vitrinasantoquia.cllxc0xjabjh.us-east-2.rds.amazonaws.com
      - DB_PORT=5432
      - DB_DATABASE=sistems
      - DB_USERNAME=sistems
      - DB_PASSWORD=daniel199132183218
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/posgresql/data"
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"


  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment: 
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    stdin_open: true
    tty: true

volumes:
  dbdata:


